import IISStomatologicheskaya_KlinikaУслугаEController from '../i-i-s-stomatologicheskaya-klinika-услуга-e';

var IISStomatologicheskaya_KlinikaУслугаENewController = IISStomatologicheskaya_KlinikaУслугаEController;
export default IISStomatologicheskaya_KlinikaУслугаENewController;
