import IISStomatologicheskaya_KlinikaДолжностьEController from '../i-i-s-stomatologicheskaya-klinika-должность-e';

var IISStomatologicheskaya_KlinikaДолжностьENewController = IISStomatologicheskaya_KlinikaДолжностьEController;
export default IISStomatologicheskaya_KlinikaДолжностьENewController;
